strictDepBuilds: true
blockExoticSubdeps: false
trustPolicy: no-downgrade
minimumReleaseAge: 1440

onlyBuiltDependencies:
  - core-js
  - es5-ext
  - esbuild

ignoredBuiltDependencies:
  - protobufjs

minimumReleaseAgeExclude:
  - accounts
  - mppx
  - incur
  - ox
  - viem

overrides:
  protobufjs: '>=7.5.5'
  tar: '>=7.5.13'
  dompurify: '>=3.4.0'

patchedDependencies:
  '@braintree/sanitize-url@7.1.2': patches/@braintree__sanitize-url@7.1.2.patch
  dayjs@1.11.20: patches/dayjs@1.11.20.patch
